repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: double-quote-string-fixer
#        exclude: manage.py
      - id: check-yaml
      - id: check-merge-conflict
  - repo: http://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: http://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
